#!/bin/bash
Mac-mini-Marina:Razrabotka marina$ again=yes
Mac-mini-Marina:Razrabotka marina$ while [ "$again" = "yes" ]
> do
> echo "Please enter a name:"
> read name
> echo "The name you entered is $name"
> echo "Do you wish to continue?"
> read again
> done
